name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: docker build -t  ${{ vars.DOCKER_HUB_NAME }} .

      - name: Push Docker image to Docker Hub
        run: docker push  ${{ vars.DOCKER_HUB_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH Deploy to VPS
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          #key: ${{ secrets.SSH_KEY }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /root/server
            ./reboot.sh
            docker pull  ${{ vars.DOCKER_HUB_NAME }}
            docker-compose restart